1. values added: 20
2. final result: 20
3. values added: 20
4. the code returns an error because the variable is declared with let which means it can only be accessed within the book and since final result is outside the block it will throw out an error
5. the code returns an error because result is a constant which cannot be reassigned
6. the code returns an error since const has the same scope as let which means it cannot be accessed outside the block